name: ProtocolSupportStuff
main: net.perfectdreams.protocolsupportstuff.ProtocolSupportStuff
version: 2.0.0
description: A plugin that does... stuff, I guess. Disable MC versions, remap items, pre-1.9 PvP and much more!
authors:
- MrPowerGamerBR
website: https://perfectdreams.net/
softdepend: ["ProtocolSupport", "ProtocolLib"]
api-version: 1.13